include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "*/.g.dart"
  errors:
    always_declare_return_types: error

linter:
  rules:
    unnecessary_await_in_return: true
    prefer_single_quotes: true
    avoid_unused_constructor_parameters: true
    always_declare_return_types: true
